package com.hanlin.pojo;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gid
     *
     * @mbg.generated
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gname
     *
     * @mbg.generated
     */
    private String gname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gid
     *
     * @return the value of grade.gid
     *
     * @mbg.generated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gid
     *
     * @param gid the value for grade.gid
     *
     * @mbg.generated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gname
     *
     * @return the value of grade.gname
     *
     * @mbg.generated
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gname
     *
     * @param gname the value for grade.gname
     *
     * @mbg.generated
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }
}